services:
  app:
    image: node:20-alpine
  shell:
    build:
      context: .
      dockerfile: apps/shell/Dockerfile
      args:
        APP_NAME: shell
    restart: always
    ports:
      - '4002:4173'
    depends_on:
      - ledgerely
      - office-admin

  ledgerely:
    build:
      context: .
      dockerfile: apps/ledgerely/Dockerfile
      args:
        APP_NAME: ledgerely
    restart: always
    ports:
      - '4000:4173'

  office-admin:
    build:
      context: .
      dockerfile: apps/office-admin/Dockerfile
      args:
        APP_NAME: office-admin
    restart: always
    ports:
      - '4001:4173'
